/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesFireSuppressionSystemsRouteImport } from './routes/guides.fire-suppression-systems'
import { Route as GuidesFireSafetyAuditChecklistRouteImport } from './routes/guides.fire-safety-audit-checklist'
import { Route as GuidesFireExtinguisherTypesRouteImport } from './routes/guides.fire-extinguisher-types'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicGscSetupRouteImport } from './routes/api/public/gsc-setup'
import { Route as ApiPublicFeedbackFallbackRouteImport } from './routes/api/public/feedback-fallback'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiAdminWebhookSettingsRouteImport } from './routes/api/admin/webhook-settings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFireSuppressionSystemsRoute =
  GuidesFireSuppressionSystemsRouteImport.update({
    id: '/guides/fire-suppression-systems',
    path: '/guides/fire-suppression-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesFireSafetyAuditChecklistRoute =
  GuidesFireSafetyAuditChecklistRouteImport.update({
    id: '/guides/fire-safety-audit-checklist',
    path: '/guides/fire-safety-audit-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesFireExtinguisherTypesRoute =
  GuidesFireExtinguisherTypesRouteImport.update({
    id: '/guides/fire-extinguisher-types',
    path: '/guides/fire-extinguisher-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/admin/webhooks',
  path: '/admin/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGscSetupRoute = ApiPublicGscSetupRouteImport.update({
  id: '/api/public/gsc-setup',
  path: '/api/public/gsc-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackFallbackRoute =
  ApiPublicFeedbackFallbackRouteImport.update({
    id: '/api/public/feedback-fallback',
    path: '/api/public/feedback-fallback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWebhookSettingsRoute = ApiAdminWebhookSettingsRouteImport.update({
  id: '/api/admin/webhook-settings',
  path: '/api/admin/webhook-settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/fire-extinguisher-types': typeof GuidesFireExtinguisherTypesRoute
  '/guides/fire-safety-audit-checklist': typeof GuidesFireSafetyAuditChecklistRoute
  '/guides/fire-suppression-systems': typeof GuidesFireSuppressionSystemsRoute
  '/api/admin/webhook-settings': typeof ApiAdminWebhookSettingsRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/feedback-fallback': typeof ApiPublicFeedbackFallbackRoute
  '/api/public/gsc-setup': typeof ApiPublicGscSetupRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/fire-extinguisher-types': typeof GuidesFireExtinguisherTypesRoute
  '/guides/fire-safety-audit-checklist': typeof GuidesFireSafetyAuditChecklistRoute
  '/guides/fire-suppression-systems': typeof GuidesFireSuppressionSystemsRoute
  '/api/admin/webhook-settings': typeof ApiAdminWebhookSettingsRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/feedback-fallback': typeof ApiPublicFeedbackFallbackRoute
  '/api/public/gsc-setup': typeof ApiPublicGscSetupRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/fire-extinguisher-types': typeof GuidesFireExtinguisherTypesRoute
  '/guides/fire-safety-audit-checklist': typeof GuidesFireSafetyAuditChecklistRoute
  '/guides/fire-suppression-systems': typeof GuidesFireSuppressionSystemsRoute
  '/api/admin/webhook-settings': typeof ApiAdminWebhookSettingsRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/feedback-fallback': typeof ApiPublicFeedbackFallbackRoute
  '/api/public/gsc-setup': typeof ApiPublicGscSetupRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/admin/webhooks'
    | '/api/chat'
    | '/guides/fire-extinguisher-types'
    | '/guides/fire-safety-audit-checklist'
    | '/guides/fire-suppression-systems'
    | '/api/admin/webhook-settings'
    | '/api/public/chat'
    | '/api/public/feedback'
    | '/api/public/feedback-fallback'
    | '/api/public/gsc-setup'
    | '/api/public/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/admin/webhooks'
    | '/api/chat'
    | '/guides/fire-extinguisher-types'
    | '/guides/fire-safety-audit-checklist'
    | '/guides/fire-suppression-systems'
    | '/api/admin/webhook-settings'
    | '/api/public/chat'
    | '/api/public/feedback'
    | '/api/public/feedback-fallback'
    | '/api/public/gsc-setup'
    | '/api/public/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/admin/webhooks'
    | '/api/chat'
    | '/guides/fire-extinguisher-types'
    | '/guides/fire-safety-audit-checklist'
    | '/guides/fire-suppression-systems'
    | '/api/admin/webhook-settings'
    | '/api/public/chat'
    | '/api/public/feedback'
    | '/api/public/feedback-fallback'
    | '/api/public/gsc-setup'
    | '/api/public/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  ApiChatRoute: typeof ApiChatRoute
  GuidesFireExtinguisherTypesRoute: typeof GuidesFireExtinguisherTypesRoute
  GuidesFireSafetyAuditChecklistRoute: typeof GuidesFireSafetyAuditChecklistRoute
  GuidesFireSuppressionSystemsRoute: typeof GuidesFireSuppressionSystemsRoute
  ApiAdminWebhookSettingsRoute: typeof ApiAdminWebhookSettingsRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicFeedbackFallbackRoute: typeof ApiPublicFeedbackFallbackRoute
  ApiPublicGscSetupRoute: typeof ApiPublicGscSetupRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/fire-suppression-systems': {
      id: '/guides/fire-suppression-systems'
      path: '/guides/fire-suppression-systems'
      fullPath: '/guides/fire-suppression-systems'
      preLoaderRoute: typeof GuidesFireSuppressionSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/fire-safety-audit-checklist': {
      id: '/guides/fire-safety-audit-checklist'
      path: '/guides/fire-safety-audit-checklist'
      fullPath: '/guides/fire-safety-audit-checklist'
      preLoaderRoute: typeof GuidesFireSafetyAuditChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/fire-extinguisher-types': {
      id: '/guides/fire-extinguisher-types'
      path: '/guides/fire-extinguisher-types'
      fullPath: '/guides/fire-extinguisher-types'
      preLoaderRoute: typeof GuidesFireExtinguisherTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gsc-setup': {
      id: '/api/public/gsc-setup'
      path: '/api/public/gsc-setup'
      fullPath: '/api/public/gsc-setup'
      preLoaderRoute: typeof ApiPublicGscSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback-fallback': {
      id: '/api/public/feedback-fallback'
      path: '/api/public/feedback-fallback'
      fullPath: '/api/public/feedback-fallback'
      preLoaderRoute: typeof ApiPublicFeedbackFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/webhook-settings': {
      id: '/api/admin/webhook-settings'
      path: '/api/admin/webhook-settings'
      fullPath: '/api/admin/webhook-settings'
      preLoaderRoute: typeof ApiAdminWebhookSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  ApiChatRoute: ApiChatRoute,
  GuidesFireExtinguisherTypesRoute: GuidesFireExtinguisherTypesRoute,
  GuidesFireSafetyAuditChecklistRoute: GuidesFireSafetyAuditChecklistRoute,
  GuidesFireSuppressionSystemsRoute: GuidesFireSuppressionSystemsRoute,
  ApiAdminWebhookSettingsRoute: ApiAdminWebhookSettingsRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicFeedbackFallbackRoute: ApiPublicFeedbackFallbackRoute,
  ApiPublicGscSetupRoute: ApiPublicGscSetupRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
